{% set name = "celery" %}
{% set version = "5.2.0" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 4d858a8fe53c07a9f0cbf8cf1da28e8abe5464d0aba5713bf83908e74277734b
    patches:
        - 0001-skip-a-test.patch

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    entry_points:
        - celery = celery.__main__:main

requirements:
    build:
        - python
        - pip
    run:
        - python
        - click-didyoumean
        - click-repl
        - click-plugins
        - pytz
        - billiard>=3.6.3,<4.0
        - kombu>=4.6.10,<4.7
        - future >=0.18.0
        - vine 1.3.0.*
        - sqlalchemy
        - cryptography
    run_constrained:
        - sphinx >=2.0

test:
    requires:
        - case >=1.3.1
        - pytest >=4.5.0,<5.3.5
        - pytest-subtests
        - boto3 >1.9.178
        - moto 1.3.7.*
    source_files:
        - t
    imports:
        - celery
        - celery.app
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.utils
        - celery.utils.dispatch
        - celery.worker
    commands:
        - celery --version
        - celery worker --help
        - celery beat --help
        - celery multi help
        - celery shell --help
        - pytest t/unit  # [py3k]

about:
    home: http://celeryproject.org
    license_file: LICENSE
    license: BSD-3-Clause
    summary: Distributed Task Queue
    dev_url: https://github.com/celery/celery
    doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
    recipe-maintainers:
        - kwilcox
        - pmlandwehr
        - sodre
        - edetec
