{% set name = "celery" %}
{% set version = "5.1.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 54436cd97b031bf2e08064223240e2a83d601d9414bcb1b702f94c6c33c29485
    patches:
        - 0001-skip-a-test.patch

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"
    entry_points:
        - celery = celery.__main__:main

requirements:
    build:
        - git
        - patch  # [not win]
        - m2-patch  # [win]
    host:
        - python >=3.6
        - pip
        - setuptools
        - wheel
    run:
        - python >=3.6
        - click >=7.0,<8.0
        - click-didyoumean >=0.0.3
        - click-repl >=0.1.6
        - click-plugins >=1.1.1
        - pytz
        - billiard >=3.6.4.0,<4.0
        - kombu >=5.0.0,<6.0
        #- future >=0.18.0
        - vine >=5.0.0,<6.0
        - sqlalchemy
        - cryptography
    run_constrained:
        - sphinx >=2.0

test:
    requires:
        - boto3 >=1.9.178
        - case >=1.3.1
        - moto ==1.3.7
        - pytest 6.2.*
        #- pytest-celery
        - pytest-timeout 1.4.2.*
        - pytest-subtests
    source_files:
        - t
    imports:
        - celery
        - celery.app
        - celery.app.task
        - celery.apps
        - celery.backends
        - celery.backends.database
        - celery.bin
        - celery.concurrency
        - celery.contrib
        - celery.events
        - celery.fixups
        - celery.loaders
        - celery.security
        - celery.utils
        - celery.utils.dispatch
        - celery.worker
    commands:
        - celery --version
        - celery worker --help
        - celery beat --help
        - celery multi help
        - celery shell --help
        - pytest t/unit  # [py3k]

about:
    home: http://celeryproject.org
    license_file: LICENSE
    license: BSD-3-Clause
    lisense_family: BSD
    summary: Distributed Task Queue
    dev_url: https://github.com/celery/celery
    doc_url: http://docs.celeryproject.org/en/latest/index.html

extra:
    recipe-maintainers:
        - kwilcox
        - pmlandwehr
        - sodre
        - edetec
